' Gambas module file

'#################################################
' Software sotto licenza GPL v3 o superiore
' Software under GPL v3 o more licence
' Francesco "Ceskho OpenCode" Apruzzese
' per info o segnalazioni scrivere a :
' cescoap@gmail.com
'#################################################

'array delle estrazioni
 estrazione0 AS String[1]
 estrazione1 AS String[1]
'-- array numero estratto
 n AS Integer[1]
'-- indice estrazione
 indice AS Integer
'-- switcher di array
 warray AS Boolean

PUBLIC FUNCTION lotto()
  
  DIM i AS Integer    '-- contatore per estrazioni
  DIM j AS Integer    '-- ""  ""     ""   ""

  n.resize(5)

FOR i = 1 TO FMain.ValueBox1.value

  nuova_estrazione(45, TRUE)

  FOR j = 0 TO 4
    '-- gestione della variabile per l'abilitazione di un solo array
    IF (estrazione0.count = 0) THEN warray = 1
    IF (estrazione1.count = 0) THEN warray = 0
    IF (estrazione0.count > 0 AND estrazione1.count > 0) THEN warray = Int(Rnd(0, 2))
    
    '-- gestione estrazione dai due array
    IF warray = 0 THEN 
      indice = Int(Rnd(0, estrazione0.count))
      n[j] = estrazione0[indice]
      estrazione0.remove(indice)
      estrazione0.resize(estrazione0.count)
    ELSE 
      indice = Int(Rnd(0, estrazione1.count))
      n[j] = estrazione1[indice]
      estrazione1.remove(indice)
      estrazione1.resize(estrazione1.count)
    END IF
  NEXT 

  n.sort(gb.Ascent)

  FOR j = 0 TO 4
    FMain.TextArea1.Text &= Str(n[j]) & "\t"
  NEXT 

    FMain.TextArea1.Text &= "\t\t\t\t\t# " & ("Lotto con sistema standard")
    FMain.TextArea1.Text &= gb.NewLine

NEXT

END

PUBLIC FUNCTION enalotto()
  
  DIM i AS Integer    '-- contatore per estrazioni
  DIM j AS Integer    '-- ""  ""     ""   ""

  n.resize(8)

FOR i = 1 TO FMain.ValueBox1.value

  nuova_estrazione(45, TRUE)

  FOR j = 0 TO 7
    '-- gestione della variabile per l'abilitazione di un solo array
    IF (estrazione0.count = 0) THEN warray = 1
    IF (estrazione1.count = 0) THEN warray = 0
    IF (estrazione0.count > 0 AND estrazione1.count > 0) THEN warray = Int(Rnd(0, 2))
    '-- gestione estrazione dai due array
    IF warray = 0 THEN 
      indice = Int(Rnd(0, estrazione0.count))
      n[j] = estrazione0[indice]
      estrazione0.remove(indice)
      estrazione0.resize(estrazione0.count)
    ELSE 
      indice = Int(Rnd(0, estrazione1.count))
      n[j] = estrazione1[indice]
      estrazione1.remove(indice)
      estrazione1.resize(estrazione1.count)
    END IF
  NEXT 

  n.sort(gb.Ascent)

  FOR j = 0 TO 7
    FMain.TextArea1.Text &= Str(n[j]) & "\t"
  NEXT 

  FMain.TextArea1.Text &= "\t\t# " & ("Superenalotto con sistema standard")
  FMain.TextArea1.Text &= gb.NewLine
  
NEXT

END

PUBLIC FUNCTION win()

  DIM i AS Integer    '-- contatore per estrazioni
  DIM j AS Integer    '-- ""  ""     ""   ""

  n.resize(10)

FOR i = 1 TO FMain.ValueBox1.value

  nuova_estrazione(20, FALSE)

  FOR j = 0 TO 9
      indice = Int(Rnd(0, estrazione0.count))
      n[j] = estrazione0[indice]
      estrazione0.remove(indice)
      estrazione0.resize(estrazione0.count)
  NEXT 
  
    n.sort(gb.Ascent)

  FOR j = 0 TO 9
    FMain.TextArea1.Text &= Str(n[j]) & "\t"
  NEXT 

  FMain.TextArea1.Text &= "# " & ("Win4Life con sistema standard")
  FMain.TextArea1.Text &= gb.NewLine

NEXT

END

PUBLIC FUNCTION dieci()
  
  DIM i AS Integer    '-- contatore per estrazioni
  DIM j AS Integer    '-- ""  ""     ""   ""

  n.resize(10)

FOR i = 1 TO FMain.ValueBox1.value

  nuova_estrazione(45, TRUE)

  FOR j = 0 TO 9
    '-- gestione della variabile per l'abilitazione di un solo array
    IF (estrazione0.count = 0) THEN warray = 1
    IF (estrazione1.count = 0) THEN warray = 0
    IF (estrazione0.count > 0 AND estrazione1.count > 0) THEN warray = Int(Rnd(0, 2))
    '-- gestione estrazione dai due array
    IF warray = 0 THEN 
      indice = Int(Rnd(0, estrazione0.count))
      n[j] = estrazione0[indice]
      estrazione0.remove(indice)
      estrazione0.resize(estrazione0.count)
    ELSE 
      indice = Int(Rnd(0, estrazione1.count))
      n[j] = estrazione1[indice]
      estrazione1.remove(indice)
      estrazione1.resize(estrazione1.count)
    END IF
    'FMain.TextArea1.Text &= Str(n[j]) & "\t"
  NEXT 

  n.sort(gb.Ascent)

  FOR j = 0 TO 9
    FMain.TextArea1.Text &= Str(n[j]) & "\t"
  NEXT 

  FMain.TextArea1.Text &= "# " & ("10&Lotto con sistema standard")
  FMain.TextArea1.Text &= gb.NewLine

NEXT

END

PUBLIC FUNCTION nuova_estrazione(size AS Integer, secondarray AS Boolean)

    '-- variabile di gestione del ciclo for,
  DIM i AS Integer

  '-- se si effettua una nuova estrazione ristabilizza la lunghezza degli array iniziale 
  estrazione0.resize(size)
  IF secondarray THEN estrazione1.resize(size)

  '-- popola le due array
  '-- array da 1 a 45
  FOR i = 1 TO size STEP 1
    estrazione0[i - 1] = i
  NEXT 
  
  '-- array da 46 a 90. Lo abilita solo se specificato
  IF secondarray THEN 
    FOR i = 1 TO size STEP 1
      estrazione1[i - 1] = (i + 45)
    NEXT 
  END IF

  RANDOMIZE 

END
