' Gambas module file

'#################################################
' Software sotto licenza GPL v3 o superiore
' Software under GPL v3 o more licence
' Francesco "Ceskho OpenCode" Apruzzese
' per info o segnalazioni scrivere a :
' cescoap@gmail.com
'#################################################

'array delle estrazioni
 estrazione AS Integer[1]
'-- array numero estratto
 n AS Integer[1]
'-- indice estrazione
 indice AS Integer

PUBLIC FUNCTION lotto(MyList AS ListBox, MyValue AS Integer)
  
  DIM i AS Integer    '-- contatore per estrazioni
  DIM j AS Integer    '-- ""  ""     ""   ""
  DIM $result AS String

  n.resize(5)

FOR i = 1 TO FMain.ValueBox1.value

  $result = ""
  nuova_estrazione(45, TRUE)

  FOR j = 0 TO 4
    indice = Int(Rnd(0, estrazione.count))
    n[j] = Int(estrazione[indice])
    estrazione.remove(indice)
    estrazione.resize(estrazione.count)
  NEXT 

  n.sort(gb.Ascent)

  FOR j = 0 TO 4
    $result &= Str(n[j]) & "\t"
  NEXT 

  FMain.TextArea1.Text &= $result & "\t\t\t\t\t# " & ("Lotto con sistema di disparità") & gb.NewLine
  $result &= "\t\t\t\t\t# " & ("Lotto con sistema di disparità")
  MyList.Add($result)
    
NEXT

END

PUBLIC FUNCTION enalotto(MyList AS ListBox, MyValue AS Integer)
  
  DIM i AS Integer    '-- contatore per estrazioni
  DIM j AS Integer    '-- ""  ""     ""   ""
  DIM $result AS String

  n.resize(8)

FOR i = 1 TO FMain.ValueBox1.value

  $result = ""
  nuova_estrazione(45, TRUE)

  FOR j = 0 TO 7
    indice = Int(Rnd(0, estrazione.count))
    n[j] = estrazione[indice]
    estrazione.remove(indice)
    estrazione.resize(estrazione.count)
  NEXT 

  n.sort(gb.Ascent)

  FOR j = 0 TO 7
    $result &= Str(n[j]) & "\t"
  NEXT 

  FMain.TextArea1.Text &= $result & "\t\t# " & ("Superenalotto con sistema di disparità") & gb.NewLine
  $result &= "\t\t# " & ("Superenalotto con sistema di disparità")
  MyList.Add($result)
  
NEXT

END

PUBLIC FUNCTION dieci(MyList AS ListBox, MyValue AS Integer)
  
  DIM i AS Integer    '-- contatore per estrazioni
  DIM j AS Integer    '-- ""  ""     ""   ""
  DIM $result AS String

  n.resize(10)

FOR i = 1 TO FMain.ValueBox1.value

  $result = ""
  nuova_estrazione(45, TRUE)

  FOR j = 0 TO 9
      indice = Int(Rnd(0, estrazione.count))
      n[j] = estrazione[indice]
      estrazione.remove(indice)
      estrazione.resize(estrazione.count)
  NEXT 

  n.sort(gb.Ascent)

  FOR j = 0 TO 9
    $result &= Str(n[j]) & "\t"
  NEXT 

  FMain.TextArea1.Text &= $result & "# " & ("10&Lotto con sistema di disparità") & gb.NewLine
  $result &= "# " & ("10&Lotto con sistema di disparità")
  MyList.Add($result)

NEXT

END

PUBLIC FUNCTION nuova_estrazione(size AS Integer, secondarray AS Boolean)

    '-- variabile di gestione del ciclo for,
  DIM i AS Integer

  '-- se si effettua una nuova estrazione ristabilizza la lunghezza degli array iniziale 
  estrazione.resize(size)

  '-- popola le due array
  '-- array da 1 a 45
  FOR i = 1 TO size STEP 1
    estrazione[i - 1] = ((i - 1) * 2) + 1 
  NEXT 

  RANDOMIZE 

END
