' Gambas module file

'#################################################
' Software sotto licenza GPL v3 o superiore
' Software under GPL v3 o more licence
' Francesco "Ceskho OpenCode" Apruzzese
' per info o segnalazioni scrivere a :
' cescoap@gmail.com
'#################################################

PUBLIC CONST DatabaseName AS String = "moneymanager"
PUBLIC CONST DatabaseTableName AS String = "money"
PUBLIC CONST LottoDatabaseName AS String = "old_extrac"
PUBLIC CONST LottoDatabaseTableName AS String = "old"
PUBLIC DatabasePath AS String = User.Home &/ ".meganalotto"
PUBLIC CONST DatabaseType AS String = "sqlite3"

PUBLIC $Value AS String = "€"

PUBLIC FUNCTION MoveDatabase()

  IF NOT Exist(DatabasePath &/ DatabaseName) THEN 
    IF NOT Exist(DatabasePath) THEN MKDIR DatabasePath
    COPY Application.Path &/ "other" &/ DatabaseName TO DatabasePath &/ DatabaseName
    PRINT "New Money Manager DataBase created in " & DatabasePath
  END IF
  
  IF NOT Exist(DatabasePath &/ LottoDatabaseName) THEN 
    IF NOT Exist(DatabasePath) THEN MKDIR DatabasePath
    COPY Application.Path &/ "other" &/ LottoDatabaseName TO DatabasePath &/ LottoDatabaseName
    PRINT "New Lotto DataBase created in " & DatabasePath
  END IF
  
END

PUBLIC FUNCTION EditDatabase(pIndice AS Integer, pData AS String, pLottery AS String, pPlayed AS String, pWinned AS String, pNote AS String)

  DIM sName AS String  ' sName è una variabile che indica il nome che diamo al nostro database
  DIM sPercorso AS String ' indica il percoso in cui andremo a creare il db
  DIM $hConn AS NEW Connection
  DIM hres AS Result
  DIM sql AS String

  DIM $id AS String = pIndice
  DIM $date AS String = pData
  DIM $lottery AS String = pLottery
  DIM $played AS String = pPlayed
  DIM $winned AS String = pWinned
  DIM $note AS String = pNote

  WITH $hConn
    .Type = DatabaseType
    .Host = DatabasePath
  END WITH 
  $hConn.Name = DatabaseName
  $hConn.Open

  $date = Split($date, "/")[2] & Split($date, "/")[1] & Split($date, "/")[0]

  hres = $hConn.edit(DatabaseTableName, "indice=" & $id)

  hres!lottery = $lottery
  hres!data = $date
  hres!note = $note
  hres!used = $played 
  hres!win = $winned

  hres.Update
  $hconn.Commit
  $hConn.Close

END

