' Gambas module file

'#################################################
' Software sotto licenza GPL v3 o superiore
' Software under GPL v3 o more licence
' Francesco "Ceskho OpenCode" Apruzzese
' per info o segnalazioni scrivere a :
' cescoap@gmail.com
'#################################################

PUBLIC NumbersString AS String

PUBLIC FUNCTION Name2Num(name AS String) AS Integer

  DIM i, valore, numb AS Integer = 0
  DIM $char AS String

    '-- exit if the string is empty
  IF name = "" THEN RETURN 0

    '-- assign a number to every letter
  FOR i = 0 TO Len(name)
      '-- find one letter for time
    PRINT Right(Left(name, i), 1)
    $char = Right(Left(name, i), 1)
    $char = LCase$($char)

    IF ($char = "a" OR $char = "k" OR $char = "u") THEN 
      valore += 1
    ELSE IF ($char = "b" OR $char = "l" OR $char = "v") THEN 
      valore += 2
    ELSE IF ($char = "c" OR $char = "m" OR $char = "w") THEN 
      valore += 3
    ELSE IF ($char = "d" OR $char = "n" OR $char = "x") THEN 
      valore += 4
    ELSE IF ($char = "e" OR $char = "o" OR $char = "y") THEN 
      valore += 5
    ELSE IF ($char = "f" OR $char = "p" OR $char = "z") THEN 
      valore += 6
    ELSE IF ($char = "g" OR $char = "q") THEN
      valore += 7
    ELSE IF ($char = "h" OR $char = "r") THEN
      valore += 8
    ELSE IF ($char = "i" OR $char = "s") THEN
      valore += 9
    ELSE IF ($char = "j" OR $char = "t") THEN
      valore += 0
    END IF

  NEXT

    '-- return only number from 1 TO 90
  IF valore < 91 THEN 
    RETURN valore
  ELSE 
    valore = valore MOD 90
    PRINT valore
    RETURN valore
  END IF

END

